### ISSUE TITLE
Remove hardcoded file name for GRU netcdf file

### ISSUE THREAD

**Issue by bartnijssen** [NCAR/summa#105]
The file name for the netcdf file that contains GRU info is hardcoded and should be read in through the file manager.

**Comment by bartnijssen** [comment]
@luckymichael and @anewman89 : Can you update this? Has this been fixed or is the filename still hardcoded?

**Comment by luckymichael** [comment]
GRU info is now read through the `LOCAL_ATTRIBUTES` netCDF file, which can be specified in the file manager.
