### ISSUE TITLE
Failure to converge with `gfortran-mp-6`

### ISSUE THREAD

**Issue by bartnijssen** [NCAR/summa#119]
When the model is run with PR #25, the test runs fail to converge (and exit) when the model is compiled with `gfortran-mp-6` on `OS X 10.11.4`. The model exits with the following error message:

```
FATAL ERROR: coupled_em/dt_temp is below the minimum time step
coupled_em/dt_temp is below the minimum time step
```

For the following cases:
```
* summaTestCases/settings/wrrPaperTestCases/figure06/summa_zDecisions_reynoldsConstantDecayRate.txt
* summaTestCases/settings/wrrPaperTestCases/figure06/summa_zDecisions_reynoldsVariableDecayRate.txt
* summaTestCases/settings/wrrPaperTestCases/figure06/summa_zDecisions_senatorConstantDecayRate.txt
* summaTestCases/settings/wrrPaperTestCases/figure06/summa_zDecisions_senatorVariableDecayRate.txt
* summaTestCases/settings/wrrPaperTestCases/figure09/summa_zDecisions_distributedTopmodel.txt
```
At this time it is not clear whether the error lies with `gfortran-mp-6` which is still in pre-release mode or whether this is a result of the change in numerics.

**Comment by martynpclark** [comment]
The identical convergence problems occur when compiling with gfortran 4.9.2 (no issues are encountered using ifort).

Currently exploring differences in run-time behavior when compiling using gfortran and ifort.

**Comment by bartnijssen** [comment]
Could it be an initialization issue, where a variable is used uninitialized (for that timestep) in gfortran, but initialized to zero in ifort?

**Comment by luckymichael** [comment]
This is a compiler option. It should be the same if they used same compiler options.

**Comment by bartnijssen** [comment]
Do you know what the compiler option is for gfortran to make this happen?

**Comment by luckymichael** [comment]
https://gcc.gnu.org/onlinedocs/gcc-3.4.2/g77/Variables-Assumed-To-Be-Zero.html

**Comment by bartnijssen** [comment]
Is that the same for `fortran`? We are not using `g77` (although maybe that is just an alias these days). I'll run a test with `-finit-local-zero`. If it turns out that that help we need to fix the code, because it means a variable is not initialized.

**Comment by bartnijssen** [comment]
OK - worth a try but it made no difference. Still fails to converge.

**Comment by bartnijssen** [comment]
@bartnijssen: Need to confirm whether this bug still exists

**Comment by bartnijssen** [comment]
Error no longer occurs on `develop` with commit b8883ee5c6637a0c3060a637001c86264fa7d723. 

Tested on OS X 10.11.6, with 

`COLLECT_GCC=gfortran-mp-6
COLLECT_LTO_WRAPPER=/opt/local/libexec/gcc/x86_64-apple-darwin15/6.1.0/lto-wrapper
Target: x86_64-apple-darwin15
Configured with: /opt/local/var/macports/build/_opt_mports_dports_lang_gcc6/gcc6/work/gcc-6.1.0/configure --prefix=/opt/local --build=x86_64-apple-darwin15 --enable-languages=c,c++,objc,obj-c++,lto,fortran,java --libdir=/opt/local/lib/gcc6 --includedir=/opt/local/include/gcc6 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-6 --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-6 --with-gxx-include-dir=/opt/local/include/gcc6/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local --enable-stage1-checking --disable-multilib --enable-lto --enable-libstdcxx-time --with-build-config=bootstrap-debug --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --with-pkgversion='MacPorts gcc6 6.1.0_0'
Thread model: posix
gcc version 6.1.0 (MacPorts gcc6 6.1.0_0) `

Closing issue.
