### ISSUE TITLE
Add a allocate function to allow compilation of latest code with gfortran-mp-5

### ISSUE THREAD

**Issue by bartnijssen** [NCAR/summa#120]
`gfortran` prior to version 6 does not support 

`ALLOCATE (var(allocate-shape-spec-list), SOURCE=array-source-expr)`

This is a known problem, see for example https://gcc.gnu.org/bugzilla/show_bug.cgi?id=44672

To allow compilation with older `gfortran` versions (and allow more extensive testing) we should write this function and only use it if it is not available.

**Comment by bartnijssen** [comment]
Note that this will also allow our `travis-ci` checks to pass again (`gcc-6` is not yet supported on travis).

**Comment by martynpclark** [comment]
Completed. SUMMA now compiles on gfortran 4.9.2. The convergence problem still exists.
