### ISSUE TITLE
improve handling of initial conditions

### ISSUE THREAD

**Issue by martynpclark** [NCAR/summa#125]
Add capabilities to read initial conditions from a NetCDF file. This addresses many areas of ugliness in the current code, especially where
(1) In `multi_driver.f90` there is temporary code to get the number of snow and soil layers from the ASCII initial conditions file;
(2) The same initial conditions are currently used for all HRUs
(3) There is currently no capability to add initial conditions for basin-average state variables;
(4) Errors in the initial conditions are currently recoverable, where they should be fatal.

**Comment by martynpclark** [comment]
Also, need to include the definition of the restart frequency in the config files.

**Comment by bartnijssen** [comment]
@martynpclark : Does this include the capability for exact restarts or should that be a separate issue?

Exact restart means that the model should be able to start from a saved model state and reproduce bit-for-bit the same answer as a continuous run.

**Comment by bartnijssen** [comment]
@greyNearing : Can you update on whether we have exact restart capability (netcdf state file)?

**Comment by bartnijssen** [comment]
Closed - superseded by #253
