### ISSUE TITLE
refactor multi_driver.f90 to separate out the prelimiaries from the model run

### ISSUE THREAD

**Issue by martynpclark** [NCAR/summa#131]
It will be nice to put all of this pre-processing into a single subroutine, so that inside these driver loops, we just have a set of essentially 3 calls to timestep_preprocess and 'run_timestepand 'timestep_postprocess, or something to that effect.

Perhaps more specificity than that, but the major point being to consolidate the driver to be as close as possible to just being (i) initialization, (ii) a set of nested loops over space and time containing the model run, and (iii) whatever cleanup is necessary.

**Comment by bartnijssen** [comment]
@martynpclark : Does this need further work or has this been accomplished as part of one of the earlier refactors?

**Comment by bartnijssen** [comment]
We should probably revisit this in the context of the SUMMA-LIS integration

**Comment by bartnijssen** [comment]
Bumped milestone since 2.0 has been released

**Comment by bartnijssen** [comment]
Basically done as part of PR #335 

Closing for now
