### ISSUE TITLE
Better organize model constants

### ISSUE THREAD

**Issue by martynpclark** [NCAR/summa#140]
Suggest we think of the different types of global constants. These can include:
- Physical constants
- Limits used for error checking
- Flags (e.g., missing values)

Once we have the different categories defined we can reorganize the code to clarify the role of the different constants.

It will also be good to separate global constants from global data structures, and in doing so will enable better flow of information.

**Comment by bartnijssen** [comment]
@martynpclark : Was this sufficiently address as part of #137 and #139 or does this need another round?

**Comment by martynpclark** [comment]
This was completed as part of the SUMMAv2 development.
