### ISSUE TITLE
Treatment of mixed organic / mineral soil for permfrost simulations

### ISSUE THREAD

**Issue by Musselman** [NCAR/summa#147]
Opening an issue to discuss possibility of restructuring the soil component of SUMMA to include: 1) layer-specific soil properties and 2) inclusion of soil organic content. It would be helpful for me to hear your thoughts on feasibility and challenges. 

SUMMA currently permits soil sand, silt and clay percentages as input variables but excludes organic material, which has unique thermal and hydraulic properties (high porosity, low thermal conductivity, high heat capacity). While ignoring organic material (i.e., peat) is appropriate for most regions, Arctic and Boreal areas have particularly high organic content in the upper soil column, with underlying mineral soils. In addition to determining surface thermal and water content properties, organic soils and frozen ground cause sub-surface flow paths to evolve in complex ways as soils thaw below the organic layer in summer and permit flow through the underlying, permeable mineral soils. 

Martyn has suggested referring to the structure outlined in _Lawrence and Slater (2008) Incorporating organic soil into a global climate model_ to permit the treatment of layer-specific soil properties.

[Lawrence_Slater_organic_soils.pdf](https://github.com/NCAR/summa/files/247614/Lawrence_Slater_organic_soils.pdf)

**Comment by bartnijssen** [comment]
See also #175

**Comment by martynpclark** [comment]
This is complete.
