### ISSUE TITLE
reorganize data structures

### ISSUE THREAD

**Issue by martynpclark** [NCAR/summa#15]
I'd like to make a couple of changes.

First, I'd like to split the mvar_data structure into three separate structures: state variables, fluxes, and diagnostic variables (need a better name for diagnostic variables, because a flux is also a diagnostic variable). This is important because (a) we only need storage for the fluxes, and this will help memory; (b) having a separate data structure for fluxes is important to compute time step average across all model fluxes.

Second, I'd like to add a depth dimension to the model parameter structure. This will be important if we want to have different soil parameters at different depths (e.g., sand overlying clay), and, later, when we have multi-layer veg, to have different veg properties for different veg layers.

**Comment by bartnijssen** [comment]
First part of this issue was completed. The second part is continued in #175
