### ISSUE TITLE
Improving Output Statistics

### ISSUE THREAD

**Issue by luckymichael** [NCAR/summa#159]
The `time` array in outputs are all **ZERO**. 
 
correct units for `total` statistics for flux variables, e.g. changing from `m s-1` to `m` or `m / (the length of time for summation)` for `SurfaceRunoff_total`. 

calculating total for state variables has no meaning such as `CanopyTemp_total`. maybe we can skip writing them. 

The long names of the variables need to be modified to include the statistical information. They are currently all identical for the same variable even of different statistics. 

It's great to add an option of outputting **monthly** statistics. users are not able to do that using fixed frequency output (the current method).

**Comment by greyNearing** [comment]
`The time array in outputs are all ZERO.`

This is fixed.

`correct units for total statistics for flux variables, e.g. changing from m s-1 to m or m / (the length of time for summation) for SurfaceRunoff_total.`

This is fixed.

`calculating total for state variables has no meaning such as CanopyTemp_total. maybe we can skip writing them.`

Now returns an error if the user requests an output that is not meaningful.

`The long names of the variables need to be modified to include the statistical information. They are currently all identical for the same variable even of different statistics.`

The long names of variables now include the integration information. 

`It's great to add an option of outputting monthly statistics. users are not able to do that using fixed frequency output (the current method).`

I guess that we decided to go with timetstep outputs. Perhaps in the future we can go with (or add) X by hour/day/month/year outputs, but this timestep solution seemed to give more flexibility overall.

**Comment by greyNearing** [comment]
I suggest closing this issue as solved. 
Thanks, Michael, for the careful attention.

**Comment by luckymichael** [comment]
Great. Thanks for addressing the comments Grey. I am going to close it as solved.
