### ISSUE TITLE
Implement explicit Euler solution for cases when the solution does not converge

### ISSUE THREAD

**Issue by martynpclark** [NCAR/summa#177]
Presently summa reduces the length of the time step when the solution does not converge, and "exits gracefully" (i.e., fails) if the length of the time step is below a prescribed threshold. For continuous simulations it is necessary to accept a sub-optimal solution, and here will accept the explicit Euler solution for small time steps.

**Comment by bartnijssen** [comment]
@martynpclark : is this still active? Or can we close this because a) it's already implemented; and b) you are trying something different already (operator-splitting). Please close if no longer active

**Comment by martynpclark** [comment]
I did implement the explicit Euler solution for cases when summa was slow to converge. This solution required very small time steps for cases where the equations were highly non-linear, and speed up was minimal. This approach was abandoned.
