### ISSUE TITLE
Clean trailing whitespace

### ISSUE THREAD

**Issue by bartnijssen** [NCAR/summa#216]
The SUMMA coding conventions (https://github.com/NCAR/summa/blob/master/docs/howto/summa_coding_conventions.md) specify that the user should (4 under whitespace):

_Strip all trailing whitespace (spaces at the end of a line or on a whiteline). Most editors have a setting that will automatically do this when a file is saved. This will make for much cleaner commits._

This has not happened at all and now that multiple people start working on the code it makes for pretty horrible looking PRs (e.g. PR #215), because if your editor does strip trailing whitespace (as required by the spec), it results in lots of insignificant whitespace changes.

We should undertake the following steps:
1. Run a filter over the entire repo to strip all trailing whitespace and commit that as a separate commit

2. All contributors need to modify their editor settings to automatically strip trailing whitespace at least when they are working on summa code. 
In atom trailing whitespace is stripped by default on save (you can modify this in the whitespace package that ships with atom).
In vim you can make this filetype specific by editing your `.vimrc` file: http://vim.wikia.com/wiki/Remove_unwanted_spaces

**Comment by arbennett** [comment]
This was solved in #279
