### ISSUE TITLE
Clean up file manager

### ISSUE THREAD

**Issue by bartnijssen** [NCAR/summa#217]
SUMMA file manager requires the specification of a number of files that are not in use anymore (e.g. `META_TIME`). Clean up the file manager (and some of the other setup files) so that only required files need to be specified.

**Comment by bartnijssen** [comment]
No longer used and can be removed from the code (and documentation). Note that this will also require changes to the test cases.

[ ] `META_TIME`
[ ] `META_ATTR`
[ ] `META_TYPE`
[ ] `META_FORCE`
[ ] `META_LOCALPARAM`
[ ] `META_LOCALINDEX`
[ ] `META_BASINPARAM`
[ ] `META_BASINMVAR`

**Comment by andywood** [comment]
I think I handled this in the fileManager re-org (not sure what other setup files had to be changed).
