### ISSUE TITLE
Using `ifort 17` causes crashes when reading output configuration

### ISSUE THREAD

**Issue by arbennett** [NCAR/summa#222]
As per @ougx in #203: 

>  This is actually a bug with ifort 17 that it cannot correctly detect the length of the outgoing character  array when it is an allocatable assumed-length character array. Instead the length is determined based on the content assigned to the variable. And therefore the assignment will be done compactly (continuously) in memory without spaces between elements. The content will fill the whole length of the first elements of the returning array sequentially.

This can be seen when reading the output configuration file, which has variable length.  The current implementation uses a linked list to read in all of the contents and then is supposed to transfer the data from that list into an allocatable array.  Instead of loading each node into a slot of the array it currently loads everything into the first one, which causes crashes after reading.

**Comment by bartnijssen** [comment]
Closed per #219
