### ISSUE TITLE
Canopy wind speed and resistance contribution do not take snow depth into account

### ISSUE THREAD

**Issue by arbennett** [NCAR/summa#223]
The `aeroResist` subroutine currently uses the raw heights for `heightCanopyTop` and `heightCanopyBottom`.  They should be scaled with snow depth for both correctness and stability. A number of bugs can occur if they are not scaled correctly due to the calculations of the canopy roughness and zero plane displacement heights.

**Comment by arbennett** [comment]
#220 should fix this. Here are how the heights evolve with the fix applied:

![heights](https://i.imgur.com/Lu61NLE.png)

And zoomed in at the end we can see the canopy roughness and zero plane displacement shrink as the canopy becomes nearly covered:

![heights zoomed](https://i.imgur.com/GClKvmv.png)

Finally, this is the resulting ground roughness:

![roughness](https://i.imgur.com/CdCrgLT.png)

**Comment by arbennett** [comment]
The ground resistance plot in the previous comment is difficult to interpret, so I did a run with a constant wind speed of 5 m/s.  These are some of the results.  Again, the heights:

![heights](https://i.imgur.com/v72KCVs.png)

And the ground resistance contribution:

![ground resistance](https://i.imgur.com/no4axtb.png)

Total conductance for sensible heat:

![conductance](https://i.imgur.com/x54JJc8.png)

And finally, travel time (measurement height minus snow depth divided by conductance):

![travel time](https://i.imgur.com/xKR02J4.png)

**Comment by arbennett** [comment]
Additional plots and description can be seen in [this notebook](https://gist.github.com/arbennett/8914bc10b3c0fde605cd4234c9b83eb8)

**Comment by bartnijssen** [comment]
@arbennett - should this remain open or can this be closed following PR #220?

**Comment by arbennett** [comment]
This was fixed in #220, closing.
