### ISSUE TITLE
Docker Build Fails - Ubuntu Zesty

### ISSUE THREAD

**Issue by Castronova** [NCAR/summa#319]
The SUMMA Dockerfile fails when using Ubuntu Zesty.  I think this is because Zesty is no longer supported.  https://wiki.ubuntu.com/ZestyZapus/ReleaseNotes

![image](https://user-images.githubusercontent.com/4822372/36329825-5f1a2a16-1335-11e8-9439-2c71505131d2.png)

**Comment by bartnijssen** [comment]
closed per #320
