### ISSUE TITLE
revise treatment of the measurement height

### ISSUE THREAD

**Issue by martynpclark** [NCAR/summa#32]
The height of the measurement is a local attribute that is fixed in the vertical dimension. As snow accumulates the depth of the snowpack can exceed the measurement height, which makes flux computations impossible. A better solution would be the measurement height to be a height above the ground surface, hence avoiding this problem.

**Comment by bartnijssen** [comment]
@greyNearing: @martynpclark thinks you may have done this already. Can you let us know if you have worked on this and if so what was done?

**Comment by bartnijssen** [comment]
Bumped milestone since 2.0 has been released

**Comment by martynpclark** [comment]
@arbennett -- did you address this issue in your changes to canopy snow?

**Comment by bartnijssen** [comment]
@arbennett - Can you check whether this can be closed or whether this needs to remain open. If the latter add a few lines of explanation so it's clear what still needs to be fixed.

**Comment by arbennett** [comment]
This was fixed as of commit da0d108e12c68b9368b3b3103b8d6a6b31b74fac
