### ISSUE TITLE
help wanted: problem with installing summa on ubuntu

### ISSUE THREAD

**Issue by sgarrig** [NCAR/summa#330]
Hi

I have the following error when building make file:
see below
could you help me 
thanks

sebastien 
segarrigues@PCLIM82:~/Models/summa-2.0.0/build$ make
/usr/bin/gfortran-4.8 -p -g -ffree-form -fdefault-real-8 -ffree-line-length-none -fmax-errors=0 -fbacktrace -Wno-unused -Wno-unused-dummy-argument -c  /home/segarrigues/Models/summa-2.0.0/build/source/noah-mp/module_model_constants.F  /home/segarrigues/Models/summa-2.0.0/build/source/noah-mp/module_sf_noahutl.F  /home/segarrigues/Models/summa-2.0.0/build/source/noah-mp/module_sf_myjsfc.F  /home/segarrigues/Models/summa-2.0.0/build/source/noah-mp/module_sf_sfclay.F  /home/segarrigues/Models/summa-2.0.0/build/source/noah-mp/module_sf_noahlsm.F  /home/segarrigues/Models/summa-2.0.0/build/source/noah-mp/module_sf_noahmplsm.F
/usr/bin/gfortran-4.8 -p -g -Wall -ffree-line-length-none -fmax-errors=0 -fbacktrace -fcheck=bounds -c  /home/segarrigues/Models/summa-2.0.0/build/source/engine/nrtype.f90  /home/segarrigues/Models/summa-2.0.0/build/source/engine/f2008funcs.f90  /home/segarrigues/Models/summa-2.0.0/build/source/engine/nr_utility.f90  /home/segarrigues/Models/summa-2.0.0/build/source/engine/expIntegral.f90  /home/segarrigues/Models/summa-2.0.0/build/source/engine/spline_int.f90  /home/segarrigues/Models/summa-2.0.0/build/source/hookup/summaFileManager.f90  /home/segarrigues/Models/summa-2.0.0/build/source/dshare/multiconst.f90  /home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90  /home/segarrigues/Models/summa-2.0.0/build/source/dshare/data_types.f90  /home/segarrigues/Models/summa-2.0.0/build/source/dshare/globalData.f90  /home/segarrigues/Models/summa-2.0.0/build/source/dshare/flxMapping.f90  /home/segarrigues/Models/summa-2.0.0/build/source/dshare/get_ixname.f90  /home/segarrigues/Models/summa-2.0.0/build/source/dshare/ascii_util.f90  /home/segarrigues/Models/summa-2.0.0/build/source/dshare/popMetadat.f90  /home/segarrigues/Models/summa-2.0.0/build/source/dshare/outpt_stat.f90  /home/segarrigues/Models/summa-2.0.0/build/source/engine/time_utils.f90  /home/segarrigues/Models/summa-2.0.0/build/source/engine/matrixOper.f90  /home/segarrigues/Models/summa-2.0.0/build/source/engine/mDecisions.f90
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90:30.1:

 integer(i4b),parameter            :: iLength=storage_size(ixVal)  ! size of th
 1
Error: Unclassifiable statement at (1)
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90:822.88:

,parameter,public :: maxvarDecisions = storage_size(iLookDECISIONS)/iLength
                                                                           1
Error: Symbol 'ilength' at (1) has no IMPLICIT type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90:823.83:

(i4b),parameter,public :: maxvarTime      = storage_size(iLookTIME)/iLength
                                                                           1
Error: Symbol 'ilength' at (1) has no IMPLICIT type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90:824.84:

i4b),parameter,public :: maxvarForc      = storage_size(iLookFORCE)/iLength
                                                                           1
Error: Symbol 'ilength' at (1) has no IMPLICIT type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90:825.83:

(i4b),parameter,public :: maxvarAttr      = storage_size(iLookATTR)/iLength
                                                                           1
Error: Symbol 'ilength' at (1) has no IMPLICIT type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90:826.83:

(i4b),parameter,public :: maxvarType      = storage_size(iLookTYPE)/iLength
                                                                           1
Error: Symbol 'ilength' at (1) has no IMPLICIT type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90:827.84:

i4b),parameter,public :: maxvarMpar      = storage_size(iLookPARAM)/iLength
                                                                           1
Error: Symbol 'ilength' at (1) has no IMPLICIT type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90:828.83:

(i4b),parameter,public :: maxvarProg      = storage_size(iLookPROG)/iLength
                                                                           1
Error: Symbol 'ilength' at (1) has no IMPLICIT type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90:829.83:

(i4b),parameter,public :: maxvarDiag      = storage_size(iLookDIAG)/iLength
                                                                           1
Error: Symbol 'ilength' at (1) has no IMPLICIT type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90:830.83:

(i4b),parameter,public :: maxvarFlux      = storage_size(iLookFLUX)/iLength
                                                                           1
Error: Symbol 'ilength' at (1) has no IMPLICIT type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90:831.84:

i4b),parameter,public :: maxvarDeriv     = storage_size(iLookDERIV)/iLength
                                                                           1
Error: Symbol 'ilength' at (1) has no IMPLICIT type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90:832.84:

i4b),parameter,public :: maxvarIndx      = storage_size(iLookINDEX)/iLength
                                                                           1
Error: Symbol 'ilength' at (1) has no IMPLICIT type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90:833.83:

(i4b),parameter,public :: maxvarBpar      = storage_size(iLookBPAR)/iLength
                                                                           1
Error: Symbol 'ilength' at (1) has no IMPLICIT type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90:834.83:

(i4b),parameter,public :: maxvarBvar      = storage_size(iLookBVAR)/iLength
                                                                           1
Error: Symbol 'ilength' at (1) has no IMPLICIT type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90:835.86:

b),parameter,public :: maxvarVarType   = storage_size(iLookVarType)/iLength
                                                                           1
Error: Symbol 'ilength' at (1) has no IMPLICIT type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/var_lookup.f90:836.83:

(i4b),parameter,public :: maxvarStat      = storage_size(iLookStat)/iLength
                                                                           1
Error: Symbol 'ilength' at (1) has no IMPLICIT type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/data_types.f90:24.5:

 USE var_lookup,only:maxvarStat
     1
Fatal Error: Can't open module file 'var_lookup.mod' for reading at (1): Aucun fichier ou dossier de ce type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/globalData.f90:24.5:

 USE data_types,only:gru2hru_map     ! mapping between the GRUs and HRUs
     1
Fatal Error: Can't open module file 'data_types.mod' for reading at (1): Aucun fichier ou dossier de ce type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/flxMapping.f90:10.5:

 USE data_types, only: var_info        ! data type for metadata structure
     1
Fatal Error: Can't open module file 'data_types.mod' for reading at (1): Aucun fichier ou dossier de ce type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/get_ixname.f90:49.5:

 USE var_lookup,only:iLookDECISIONS                  ! indices of the named var
     1
Fatal Error: Can't open module file 'var_lookup.mod' for reading at (1): Aucun fichier ou dossier de ce type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/popMetadat.f90:21.5:

 USE data_types, only: var_info   ! data type for metadata structure
     1
Fatal Error: Can't open module file 'data_types.mod' for reading at (1): Aucun fichier ou dossier de ce type
/home/segarrigues/Models/summa-2.0.0/build/source/dshare/outpt_stat.f90:36.5:

 USE data_types,only:extended_info,dlength,ilength  ! metadata structure type
     1
Fatal Error: Can't open module file 'data_types.mod' for reading at (1): Aucun fichier ou dossier de ce type
/home/segarrigues/Models/summa-2.0.0/build/source/engine/matrixOper.f90:27.4:

USE globalData,only:globalPrintFlag
    1
Fatal Error: Can't open module file 'globaldata.mod' for reading at (1): Aucun fichier ou dossier de ce type
/home/segarrigues/Models/summa-2.0.0/build/source/engine/mDecisions.f90:23.4:

USE var_lookup, only: maxvarDecisions  ! maximum number of decisions
    1
Fatal Error: Can't open module file 'var_lookup.mod' for reading at (1): Aucun fichier ou dossier de ce type
make: *** [compile_comm] Erreur 1

**Comment by martynpclark** [comment]
You need to update the fortran compiler. SUMMA uses gfortran v6 and above.

Please see 
http://summa.readthedocs.io/en/latest/installation/SUMMA_installation/
