### ISSUE TITLE
Too much snow compaction causes errors

### ISSUE THREAD

**Issue by arbennett** [NCAR/summa#363]
There are two sub-issues that arise from a rare case when too much snow compaction occurs:
1. subsequent calculations of volumetric fractions of ice + liquid end up greater than 1
2. subsequent calculations of layer density can be too small

**Comment by bartnijssen** [comment]
@arbennett: What do you mean with the second point? I don't quite understand what it means that the density is too small ...

**Comment by arbennett** [comment]
There is a check in the snow compaction routine which ensures that layer densities are above 40 kg/m^3. This tends to happen when the layers are very small (depths below ~0.1mm) after compaction and after corrections ensuring that volumetric fractions add up to 1.

**Comment by arbennett** [comment]
This was solved via #364
