### ISSUE TITLE
Add options for different new snow density methods

### ISSUE THREAD

**Issue by NicWayand** [NCAR/summa#84]

**Comment by bartnijssen** [comment]
@NicWayand : Nic - please elaborate

**Comment by NicWayand** [comment]
There exist other methods for estimating new snow density (see quick plot below against Snoqualmie data). Currently the Hedstrom and Pomeroy 1998 method is implemented, which does have a large parameter space, but is only a function of air temperature, while some methods (Pahaut 1976) depend also on the wind speed (representing the destruction of grains allowing them to fit tighter to produce higher new snow densities).

I am working on adding in other methods. Maybe an issue was not needed? (new to github) But I just wanted to let others know to avoid any duplication of work. (Wasn't able to "assign" myself as I had thought)

**Comment by bartnijssen** [comment]
Closed per PR #85
