### ISSUE TITLE
Liquid water in the root zone exceeds capacity Error

### ISSUE THREAD

**Issue by NicWayand** [NCAR/summa#90]
Running into a strange error "liquid water in the root zone exceeds capacity", while running snow density/compaction parameter ensembles. Full error output is at (http://depts.washington.edu/mtnhydr/data/SNQ_soil_liq.tar.gz). Occurs for about 150/2186 runs. Changing from CLM layers to unlimited fixes it (no failed convergence or the root zone error). This occurs during a large snow accumulation period, but why the error about liquid water in the root zone?? 

(Note these runs are using the addDenFunc branch but the original Hedstrom and Pomeroy 1998 function)

**Comment by bartnijssen** [comment]
Need to see whether we can reproduce this error with the existing code base.

**Comment by bartnijssen** [comment]
Closed because we should be able to find these errors in a more systematic way with the large sample simulations done by @greyNearing and @luckymichael
